//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public long id { get; set; }
        public Nullable<long> category_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string slug { get; set; }
        public Nullable<decimal> price { get; set; }
        public string photo { get; set; }
        public Nullable<System.DateTime> date_view { get; set; }
        public Nullable<int> counter { get; set; }
    
        public virtual category category { get; set; }
    }
}
